import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./ui/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex justify-center">
          <div className="w-full max-w-3xl flex flex-col">
            <Nav />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
